# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d20165227349309d1884437cb13659a4c638bb25b234c382cd7db33f0faa3196a625e3d0146784fb29884eb0aec9f1c58d8ab232fd34c4fe640aa6e2255576

test:
  secret_key_base: ebc0501af3f04136a6587a72e7810c964b63345497f02381f1d7beff979b3b96ff65bf913ed403d030838735c0627e5917f092a059b713ff9f28d3e871fd99c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
